### ISSUE TITLE
What is the estimated time for this project's milestones, is there any roadmap?

### ISSUE THREAD

**Issue by sxysun** [WasmCert/WasmCert-Coq#2]
Hi,
We have a project [DeepSEA](https://github.com/CertiKProject/deepsea-preview) which is a verifying compiler for systems software written in Coq. And we are trying to add a WebAssembly backend to it, so as we are evaluating which Wasm formalization we should target, we encountered your awesome project! We are wondering what are the future plans for his project, especially when and will the sections in TODO be completed. Thanks in advance!

**Comment by conrad-watt** [comment]
Hi @sxysun, thanks for your interest in our project! We're currently in the process of planning things out for the coming academic year, but we'll hopefully have more to share soon.

Our immediate aim will be making sure the model+interpreter match the modern spec, while things like CompCert and Iris integration are more long-term goals which could shift in priority. Which milestone are you most interested in?

**Comment by sxysun** [comment]
Thanks for your update! That sounds great
I think having the model+interpreter matching the modern spec is already very suited for our project's purpose. As in our compiler what we need for Wasm formalization is to prove its semantics preservation during compilation, so just having a complete support for the language's modern spec is good enough!

**Comment by conrad-watt** [comment]
Hi @sxysun - we'd be interested in having a call with you/others working on DeepSEA in order to talk about our model in more detail and plan around your use-cases. Is it ok if I email you through the address on your github profile? Alternatively, you can contact me in the same way.

**Comment by sxysun** [comment]
Hi @conrad-watt , Absolutely! We would love that, you can use my work email xinyuan.sun@certik.org to reach me and we can set up the meeting
