### ISSUE TITLE
Why do composition and weakening typing rules appear twice (for both be_typing and e_typing)?

### ISSUE THREAD

**Issue by DKXXXL** [WasmCert/WasmCert-Coq#21]
We need composition and weakening of instruction typing for sure. However, I see that in both `be_typing` and `e_typing` we have composition and weakening
[for both be_typing](https://github.com/WasmCert/WasmCert-Coq/blob/a58b44f479367d3e023b565d43b26ceb06930cfa/theories/typing.v#L236) 
[and e_typing](https://github.com/WasmCert/WasmCert-Coq/blob/a58b44f479367d3e023b565d43b26ceb06930cfa/theories/typing.v#L512).

However, in my understanding, because of [the injection from be_typing into e_typing ](https://github.com/WasmCert/WasmCert-Coq/blob/a58b44f479367d3e023b565d43b26ceb06930cfa/theories/typing.v#L510), the existence of composition and weakening *alone* in `e_typing` seems enough to me. 

Why do we want another composition and weakening typing in `be_typing`? What's more typed syntax can these two typing rule in `be_typing` give us (that I cannot see)?

I think composition and weakening (mainly the weakening) will make the type judgement very "extrinsic". If we can remove those two from `be_typing`, then directly using `inversion` tactic on `be_typing` is possible and can make the proof a bit easier.

**Comment by raoxiaojia** [comment]
Basic expressions are the code that could appear in actual Wasm code. The type system in the main section of the Wasm spec thus describes a set of typing rules for them and is captured by `be_typing`. This is used in typing module function codes etc. As a result, `be_typing` needs to be complete on its own, and needs to include the structural rules in particular.

Administrative instructions are only defined to facilitate the formal definition of runtime behaviour, with corresponding typing rules defined (those defined in `e_typing`) to help the proof of additional properties. `e_typing` thus needs a natural extension of the structural rules that `be_typing` has.

It is true that from `e_typing`'s point of view, `be_typing` does not need its own version of structural rules. The essence here is that `be_typing` defines the actual type system and `e_typing` is only an auxiliary definition to facilitate formal proofs.
