### ISSUE TITLE
Questions on the specification of grow_memory

### ISSUE THREAD

**Issue by DKXXXL** [WasmCert/WasmCert-Coq#22]
I notice that [in `opsem.v`](https://github.com/WasmCert/WasmCert-Coq/blob/a58b44f479367d3e023b565d43b26ceb06930cfa/theories/opsem.v#L462), `r_grow_memory_success` and `r_grow_memory_failure` is assymetric as one asks for `mem_grow m (Wasm_int.N_of_uint i32m c) = Some mem` but the other doesn't ask for `mem_grow m (Wasm_int.N_of_uint i32m c) = None` 

Why here the condition (argument) of `r_grow_memory_success` and `r_grow_memory_failure` are assymetric compared to other success/failure operations? (Say, `r_store_success` and `r_store_failure` seem pretty symmetric to me. I think other success/failure operations are all pretty symmetric).

Thanks!

**Comment by raoxiaojia** [comment]
This is because `grow_memory` can fail non-deterministically (as defined in the spec), i.e. even if all the premises in the successful reduction are fulfilled, `grow_memory` is still allowed to fail (due to the embedder).
