### ISSUE TITLE
Question about `inv`, `na_inv` and atomicity in Iris-Wasm

### ISSUE THREAD

**Issue by DKXXXL** [WasmCert/WasmCert-Coq#23]
Hello, I have been checking out the Iris-Wasm implementation.  I am quite new to the Iris stuff.
My question is in your implementation, you implemented the [atomicity seemingly for the sake of invariant](https://github.com/WasmCert/WasmCert-Coq/blob/2195cd5ef6c32042ee302376d5ebd80e3b5cd67e/theories/iris/language/iris_atomicity.v#L16)
But when doing logical relation proof, you use `na_inv` non-atomic invariant instead. (and in fact I don't find `inv` to be used anywhere)

It gives me a feeling that, you initially start with working with `inv` but then due to certain reasons, you change to use `na_inv`. 
If that is true, Is there a particular reason that causing `inv` not applicable in Iris-Wasm? 
I will also appreciate it if you can share some experience that when to choose `na_inv` and when to choose `inv`. Due to the limited example I touch, I don't know when `inv` is not-applicable, and on the other hand, `na_inv` seems requiring "threading" the proof

Thanks!

**Comment by opqrs** [comment]
It's a question of convenience, see for example section 10.2 of
https://plv.mpi-sws.org/iris/appendix-3.2.pdf
