### ISSUE TITLE
Licensing issues with Parseque

### ISSUE THREAD

**Issue by palmskog** [WasmCert/WasmCert-Coq#29]
I was looking at your dependencies, among which is [Parseque](https://github.com/gallais/parseque) and [MathComp](https://github.com/math-comp/math-comp). The problem with this is that Parseque is currently licensed under GPL-3.0 and MathComp is licensed under CECILL-B. According to the Free Software Foundation, these two licenses are [incompatible](https://www.gnu.org/licenses/license-list.html#CeCILL-B).

Hence, I believe you have two issues:
- the binary `.vo` files of this project can't be legally distributed, ruling out any distribution in the Coq Platform and similar
- you will likely have to switch your license from MIT to GPL-3.0, at least for affected files, since GPL-3.0 doesn't allow derivative works to have another license.

Note that this issue would have to be resolved before joining Coq-community as proposed in #28.

**Comment by spitters** [comment]
@gallais FYI

**Comment by spitters** [comment]
@palmskog What do you think about adding Parseque to coq-community? I haven't looked at the quality of the project, but generally I have a lot of respect for @gallais . Moreover, the Parseque seems to be generally useful.

**Comment by palmskog** [comment]
@spitters if someone volunteers to be the initial official maintainer of Parseque, I'm happy to facilitate the process of moving Parseque to Coq-community and shepherd the relicensing (we recommend either MIT or in case weak copyleft is desired, MPL-2.0).

Recall that an initial maintainer can step down anytime. Perhaps @womeier who did some recent commits to Parseque could be initial Parseque maintainer in Coq-community?

**Comment by raoxiaojia** [comment]
> I was looking at your dependencies, among which is [Parseque](https://github.com/gallais/parseque) and [MathComp](https://github.com/math-comp/math-comp). The problem with this is that Parseque is currently licensed under GPL-3.0 and MathComp is licensed under CECILL-B. According to the Free Software Foundation, these two licenses are [incompatible](https://www.gnu.org/licenses/license-list.html#CeCILL-B).
> 
> Hence, I believe you have two issues:
> 
> * the binary `.vo` files of this project can't be legally distributed, ruling out any distribution in the Coq Platform and similar
> * you will likely have to switch your license from MIT to GPL-3.0, at least for affected files, since GPL-3.0 doesn't allow derivative works to have another license.
> 
> Note that this issue would have to be resolved before joining Coq-community as proposed in #28.

This is a very good point! It's fortuitous that @gallais generously makes the grant. On the other hand, I don't believe we actually used any part of mathcomp outside ssreflect, which is now integrated into base Coq -- so we might be able to get rid of that dependency at some point as well. A more impending issue is the use of CompCert numerics - I believe that belongs to the open source part of it which is under LGPL (since they use Flocq floats anyway) -- but I'll need to do some further studies.

**Comment by womeier** [comment]
> @spitters if someone volunteers to be the initial official maintainer of Parseque, I'm happy to facilitate the process of moving Parseque to Coq-community and shepherd the relicensing (we recommend either MIT or in case weak copyleft is desired, MPL-2.0).
> 
> Recall that an initial maintainer can step down anytime. Perhaps @womeier who did some recent commits to Parseque could be initial Parseque maintainer in Coq-community?

sure, I can do that. (as in: make it work for new versions of Coq, I don't intend to develop new features for parseque)

**Comment by palmskog** [comment]
> sure, I can do that. (as in: make it work for new versions of Coq, I don't intend to develop new features for parseque)

There is not requirement to develop new features as maintainer, we only recommend that to keep the project working with the latest released version of Coq. I will then create a new transfer issue on Parseque in Coq-community and ping the involved people there.

**Comment by spitters** [comment]
> > I was looking at your dependencies, among which is [Parseque](https://github.com/gallais/parseque) and [MathComp](https://github.com/math-comp/math-comp). The problem with this is that Parseque is currently licensed under GPL-3.0 and MathComp is licensed under CECILL-B. According to the Free Software Foundation, these two licenses are [incompatible](https://www.gnu.org/licenses/license-list.html#CeCILL-B).
> > Hence, I believe you have two issues:
> > 
> > * the binary `.vo` files of this project can't be legally distributed, ruling out any distribution in the Coq Platform and similar
> > * you will likely have to switch your license from MIT to GPL-3.0, at least for affected files, since GPL-3.0 doesn't allow derivative works to have another license.
> > 
> > Note that this issue would have to be resolved before joining Coq-community as proposed in #28.
> 
> This is a very good point! It's fortuitous that @gallais has generously made the grant.
> 
> On the other hand, I don't believe we actually used any part of mathcomp outside ssreflect, which is now integrated into base Coq -- so we might be able to get rid of that dependency at some point as well if I understand it correctly. A more impending issue is the use of CompCert numerics - I believe that belongs to the open source part of it which is under LGPL (since they use Flocq floats anyway) -- but I'll need to do some further studies.

@raoxiaojia Xavier Leroy relicensed a version of the machine integers precisely so that it could be used in more liberal open source projects. Please let me know if you need help finding it.

**Comment by palmskog** [comment]
The relicensing in CompCert was done already in CompCert [version 3.9](https://github.com/AbsInt/CompCert/releases/tag/v3.9), so since you depend on 3.11 or later here, you should be good as long as you only depend on precisely the CompCert numerics.

**Comment by raoxiaojia** [comment]
That's what I'm hoping for as well -- I'll find sometime to study this anyway to make sure.

That seemingly suggests that, if we can get rid of the dependency on mathcomp, then the license situation is actually quite good.

**Comment by palmskog** [comment]
@raoxiaojia but since we were able to relicense Parseque with permission from its author [here](https://github.com/coq-community/parseque/pull/9), there is no longer any problem with depending on MathComp license-wise. It's fine by me if you want to remove the MathComp dependency for other reasons, but to me, this issue is solved. The only remaining thing to do is to merge https://github.com/coq/opam/pull/2834 which I will do after CI passes.
