### ISSUE TITLE
problem with update to wasm 2.0

### ISSUE THREAD

**Issue by womeier** [WasmCert/WasmCert-Coq#40]
Hello @raoxiaojia, thanks a lot for all your work on updating to 2.0!
I just updated to your 2.0 branch, and it seems there may be sth. wrong with the generated binaries?:

```
wasm2wat foo.wasm 
00002b1: error: expected ref.null or ref.func in passive element segment
00002b2: error: expected END opcode after element expression
```
Note that we only use active element segments and no passive ones, see the diff of my update to 2.0: https://github.com/womeier/certicoqwasm/commit/38ec23b07312187aca4cdca35c0cbf78e0be686a
The proof is not adjusted yet, so there may also be something wrong with it...

## Reproduce
1)  CertiCoq-Wasm (version with the update to 2.0) produces e.g. a file [foo.wasm.txt](https://github.com/WasmCert/WasmCert-Coq/files/14994868/foo.wasm.txt)
2) run wasm2wat on file
3) observe above error

## Further
I used my script [wasm_to_coq.py](https://github.com/womeier/certicoqwasm-testing/blob/master/wasm_to_coq.py) to import it in WasmCert: [foo_wasm.v.txt](https://github.com/WasmCert/WasmCert-Coq/files/14994896/foo_wasm.v.txt),  `run_parse_module` returns the module with the original elements section

<del> run_parse_module returns None </del> 
(I first forgot to add tailcalls to the parser, I'm using [this version](https://github.com/womeier/WasmCert-Coq/commits/2.0-tailcall/) of WasmCert now, which is your 2.0 branch + basic tailcall definitions).

You should observe the same for this file with your current setup, it doesn't contain tailcalls: 
[demo1.wasm.txt](https://github.com/WasmCert/WasmCert-Coq/files/14995233/demo1.wasm.txt)

**Comment by raoxiaojia** [comment]
Thanks for the report! This is also the reason I'm waiting before merging despite all proofs being done, as I've been testing random binaries with the new instructions and fixed a few things for the parser/printer yesterday.

I'll look into fixing this. All bug reports are appreciated!

**Comment by raoxiaojia** [comment]
There might be an issue on the function `table_element_mapping`:
https://github.com/womeier/certicoqwasm/blob/38ec23b07312187aca4cdca35c0cbf78e0be686a/theories/CodegenWasm/LambdaANF_to_Wasm.v#L875

The init expressions need to be of a reference type, while in your generation code a `const_num` is provided. This induces the error message (although I'm not sure why the error message also indicates a passive elem segment, as it seems that the printer is correct in this case -- maybe we can test again when you fix the bug on your code generation).

On a side note, it's also slightly weird that the error message states that the initialiser has to be `ref.null` or `ref.func` -- according to the spec, any constant expression of a reference type should be fine, so global.get should be allowed; but this is a separate issue. Maybe this is a bug of wabt?

**Comment by womeier** [comment]
Thanks for looking into it!

Indeed, that was the problem. It works now as expected with `ref.func`.
I'll report it with the `wabt` people.

**Comment by raoxiaojia** [comment]
> Thanks for looking into it!
> 
> Indeed, that was the problem. It works now as expected with `ref.func`. I'll report it with the `wabt` people.

Also, note that the type of element mode doesn't impose additional restrictions on what the initialiser expression can be (at least, not in Wasm 2.0) -- i.e. the elem being passive doesn't really invalidate any init expression that would otherwise be valid (e.g. with an active mode); so there's a case to be made that the error message is slightly misleading -- unless this has changed in a future proposal.
