### ISSUE TITLE
Update to Coq 8.19?

### ISSUE THREAD

**Issue by womeier** [WasmCert/WasmCert-Coq#46]
Hello @raoxiaojia, we're hoping to update to Coq 8.19 at some point.

Was wondering if you already have plans for that?

**Comment by raoxiaojia** [comment]
I can do it after a paper submission this week. This should be fairly easy, I don't expect anything to break except for maybe a few deprecated lemmas.

**Comment by womeier** [comment]
Sounds good, thanks.

**Comment by raoxiaojia** [comment]
Update: see #48 .

**Comment by womeier** [comment]
Just updated to 8.19. All good from my side, thanks!
