### ISSUE TITLE
opam version compatible with Coq 8.19

### ISSUE THREAD

**Issue by JasonGross** [WasmCert/WasmCert-Coq#55]
Would it be possible to tag a version compatible with Coq 8.19 and release it on opam?  I'm trying to minimize https://github.com/MetaCoq/metacoq/issues/1072 with the bug minimizer, and it seems there are no released versions of coq-wasm and coq-certicoq compatible with the same version of Coq

**Comment by raoxiaojia** [comment]
Closed as the corresponding PR on `opam-coq-archive` is merged.
