### ISSUE TITLE
TODO - instantiation bugs

### ISSUE THREAD

**Issue by conrad-watt** [WasmCert/WasmCert-Coq#6]
https://github.com/WasmCert/WasmCert-Coq/blob/4ca34c84a9ecba4af89d0fb685c7814ea8892a97/theories/instantiation.v#L826

the `s` on the referenced line should be `s'` - similarly for the line below, and the equivalent lines in the relational `instantiate` definition. Will fix as soon as I have Coq access.

**Comment by conrad-watt** [comment]
Two more bugs in Isabelle:
exports aren't checked for uniqueness
memory/table limit typing is wrong (incorrectly requires precise equality of max values)

**Comment by conrad-watt** [comment]
Another bug:
module_func_typing - the call to the body type checker should have `[]` as the input type

**Comment by conrad-watt** [comment]
Another:
https://github.com/WasmCert/WasmCert-Coq/blob/4ca34c84a9ecba4af89d0fb685c7814ea8892a97/theories/instantiation.v#L277
e_ind here should be t_ind

**Comment by conrad-watt** [comment]
> Two more bugs in Isabelle:
> exports aren't checked for uniqueness
> memory/table limit typing is wrong (incorrectly requires precise equality of max values)

This is the only one outstanding now

**Comment by raoxiaojia** [comment]
This along with other bugs are now fixed by the cumulative patches ending with 0d29c55e17f7fae71e18f884aeddcf9c5501fd69 .
